# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-card',
                'doc_host': 'https://lumiai.github.io',
                'git_url': 'https://github.com/lumiai/nbdev-card',
                'lib_path': 'nbdev_card'},
  'syms': {'nbdev_card.core': {'nbdev_card.core.foo': ('core.html#foo', 'nbdev_card/core.py')}}}
